USE [Fileworx]
GO

/****** Object:  Table [dbo].[T_News]    Script Date: 3/22/2023 7:05:07 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[T_News](
	[ID] [int] NOT NULL,
	[C_category] [varchar](255) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[T_News]  WITH CHECK ADD FOREIGN KEY([ID])
REFERENCES [dbo].[T_File] ([ID])
GO

